### ISSUE TITLE
[CHECKLIST] Docs updates

### ISSUE THREAD

**Issue by drewstone** [webb-tools/tangle-docs#6]
- Remove learn (don't need Webb bridges in Tangle)
- Check all links, add something to CI
- Add substrate to EVM conversion
- Remove DKG-Substrate
- Spin DKG stats sites down
- BABE updates
- https://github.com/webb-tools/tangle/issues/378
- Make Tangle dropdown overview active state the default
<img width="888" alt="image" src="https://github.com/webb-tools/tangle-docs/assets/13153687/19026694-8d48-4446-aaa8-108a0f6e4106">

**Comment by thomivy** [comment]
Current status

- [x] Remove learn (don't need Webb bridges in Tangle)
- [ ] Check all links, add something to CI
- [x] Add substrate to EVM conversion
- [x] Remove DKG-Substrate from Pallets list
- [ ] Spin DKG stats sites down
- [x] BABE updates
- [x] https://github.com/webb-tools/tangle/issues/378
- [x] Make Tangle dropdown overview active state the default

**Comment by thomivy** [comment]
Remaining:

  - [ ] Spin DKG stats sites down

**Comment by monaiuu** [comment]
@thomivy Can we add a section on the doc site on how restaking works? Hoping to link to doc site via below container/button on the service dashboard UI:

![Image](https://github.com/webb-tools/tangle-docs/assets/109539270/855c9e72-eb96-4c97-984b-5a86deec5384)

**Comment by monaiuu** [comment]
Also [search engine result ](https://www.google.com/search?q=tangle+tools+docs&rlz=1C5CHFA_enCA1098CA1098&oq=tangle+tools+docs&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIKCAEQABiABBiiBDIKCAIQABiABBiiBDIKCAMQABiABBiiBDIGCAQQRRg8MgYIBRBFGDwyBggGEEUYPNIBCDQzNjJqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8)for tangle docs is still displaying old favicon: 

![Image](https://github.com/webb-tools/tangle-docs/assets/109539270/a174adf7-078c-4568-9104-18d37fada4f3)
